-- Add the new fields to CLNMAS;
    ALTER TABLE CLNMAS ADD COMMON varChar(250);
    ALTER TABLE CLNMAS ADD New_CLIENT_ID INTEGER;
	GO

-- Update the COMMON field with the Common data;
    UPDATE CLNMAS SET CLNMAS.COMMON = ISNULL([CompanyName], '') + ISNULL([ADDRESS1], '') + ISNULL([HPhone], '')
	WHERE AGENCY = '4414 W Oakland Park Blvd';

-- Update the New_CLIENT_ID with the Min of the CLIENT_ID;
    SELECT CLNMAS.COMMON, Min(CLNMAS.CLIENT_ID) AS MinOfCLIENT_ID
      INTO CLNMAS_Dups FROM CLNMAS GROUP BY CLNMAS.COMMON
	WHERE COMMON IS NOT NULL;

    UPDATE CLNMAS SET New_CLIENT_ID = CLNMAS_Dups.MinOfCLIENT_ID
	  FROM CLNMAS INNER JOIN CLNMAS_Dups ON CLNMAS.COMMON = CLNMAS_Dups.COMMON
	WHERE COMMON IS NOT NULL;

    DROP TABLE CLNMAS_Dups;

-- Update CLIENT_ID on all tables;
    UPDATE POLMAS  SET POLMAS.CLIENT_ID = New_CLIENT_ID
	  FROM POLMAS  INNER JOIN CLNMAS ON CLNMAS.CLIENT_ID = POLMAS.CLIENT_ID;
    UPDATE Images  SET Images.CLIENT_ID = New_CLIENT_ID
	  FROM Images  INNER JOIN CLNMAS ON CLNMAS.CLIENT_ID = Images.CLIENT_ID;
    UPDATE Letters SET Letters.CLIENT_ID = New_CLIENT_ID
	  FROM Letters INNER JOIN CLNMAS ON CLNMAS.CLIENT_ID = Letters.CLIENT_ID;
    UPDATE MEMOMAS SET MEMOMAS.CLIENT_ID = New_CLIENT_ID
	  FROM MEMOMAS INNER JOIN CLNMAS ON CLNMAS.CLIENT_ID = MEMOMAS.CLIENT_ID;
    UPDATE PRODMAS SET PRODMAS.CLIENT_ID = New_CLIENT_ID
	  FROM PRODMAS INNER JOIN CLNMAS ON CLNMAS.CLIENT_ID = PRODMAS.CLIENT_ID;

-- Change the Agency name for the duplicates;
    UPDATE CLNMAS SET CLNMAS.AGENCY = 'HIDDEN' 
	WHERE (CLIENT_ID <> New_CLIENT_ID) AND COMMON IS NOT NULL;

-- Remove the added Fields from CLNMAS;
    ALTER TABLE CLNMAS DROP COLUMN  COMMON;
    ALTER TABLE CLNMAS DROP COLUMN  New_CLIENT_ID;
