UPDATE    POLMAS
SET
	EFFECTIVE = POLMAS_NEW.EFFECTIVE,
	EXPIRATION = POLMAS_NEW.EXPIRATION,
	PERIOD = POLMAS_NEW.PERIOD,
	PQUOTED = POLMAS_NEW.PQUOTED,
	PISSUED = POLMAS_NEW.PISSUED,
	LOB = POLMAS_NEW.LOB,
	CSR = POLMAS_NEW.CSR
FROM         POLMAS INNER JOIN
	POLMAS_NEW ON POLMAS.[UNIQUE] = POLMAS_NEW.[UNIQUE]
	AND POLMAS.Old_Client_ID = POLMAS_NEW.CLIENT_ID