UPDATE  CLNMAS
SET  LNAME = LEFT(CLNMAS_NEW.FNAME,50), FNAME = LEFT(CLNMAS_NEW.LNAME,28)
FROM  CLNMAS INNER JOIN
  CLNMAS_NEW ON CLNMAS.Old_Client_ID = CLNMAS_NEW.CLIENT_ID AND
  CLNMAS.CompanyName = CLNMAS_NEW.CompanyName AND
  CLNMAS.FNAME = CLNMAS_NEW.FNAME AND CLNMAS.LNAME = CLNMAS_NEW.LNAME