swagger: '2.0'
info:
  title: Minimal example
  version: 1.0.0

paths:
  /projects:
    get:
      $ref: '#/components/schemas/ProjectsQuery'
    post:
      $ref: '#/components/schemas/ProjectsQuery'


components:
  schemas:
    ProjectsQuery:
      summary: Get a list of projects
      tags:
        - projects
      parameters:
        - name: limit
          description: number of projects
          schema:
            type: integer
            default: 10
            maximum: 100
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
                properties:
                  projects:
                    type: array
                    description: an array of projects
