@SET dFolder="C:\QuickFL\FORMS\OLDFORMS\"

@C:
@CD C:\QuickFL\FORMS

MOVE frmAdditionalOptions.*  %dFolder%
MOVE frmApp_FloodInsurance1.*  %dFolder%
MOVE frmApp_FloodInsurance2.*  %dFolder%
MOVE frmApp_FloodPreferred.*  %dFolder%
MOVE frmApp_FloodPreferred2_050104a.*  %dFolder%
MOVE frmApp_HomeOwners_100501.*  %dFolder%
MOVE frmApp_ProducerCertification3.*  %dFolder%
MOVE frmApp_Wind_0108_Comm_citw01c_page1.*  %dFolder%
MOVE frmApp_Wind_0108_Comm_citw01c_page2.*  %dFolder%
MOVE frmApp_Wind_0108_Comm_citw01cr_Page3.*  %dFolder%
MOVE frmApp_Wind_0108_Comm_citw01cs_page1.*  %dFolder%
MOVE frmApp_Wind_0108_Comm_citw01cs_page2.*  %dFolder%
MOVE frmApp_Wind_0108_Commercial_citw01c_page1.*  %dFolder%
MOVE frmApp_Wind_0108_Commercial_citw01c_page2.*  %dFolder%
MOVE frmApp_Wind_0108_CommRes_citw01cnr_Page2.*  %dFolder%
MOVE frmApp_Wind_Comm.*  %dFolder%
MOVE frmApp_Wind_Comm_0106.*  %dFolder%
MOVE frmApp_Wind_Comm_071506.*  %dFolder%
MOVE frmApp_Wind_Comm_New.*  %dFolder%
MOVE frmApp_Wind_Comm_New_0703.*  %dFolder%
MOVE frmApp_Wind_Commercial_citw01cr1206page1.*  %dFolder%
MOVE frmApp_Wind_CommRes_citw01cr_Page1_0108.*  %dFolder%
MOVE frmApp_Wind_CommRes_citw01cr_Page1_1206.*  %dFolder%
MOVE frmApp_Wind_CommRes_citw01cr_Page2_0108.*  %dFolder%
MOVE frmApp_Wind_CommRes_citw01cr0108_Page3.*  %dFolder%
MOVE frmApp_Wind_CommRes_citw01cr1206page2.*  %dFolder%
MOVE frmApp_Wind_CommRes_citw01crc71506.*  %dFolder%
MOVE frmApp_Wind_CommRes_citw01crs_0108_Page2.*  %dFolder%
MOVE frmApp_Wind_CommRes_citw01crs_0108_Page3.*  %dFolder%
MOVE frmApp_Wind_CommRes_citw01crs_Page1_0108.*  %dFolder%
MOVE frmApp_Wind_CommRes_citw01crs_Page2_0108.*  %dFolder%
MOVE frmApp_Wind_CommRes_citw01crs_Page3_0108.*  %dFolder%
MOVE frmApp_Wind_CommRes_citw01crs1206Page1.*  %dFolder%
MOVE frmApp_Wind_CommRes_citw01crs1206Page2.*  %dFolder%
MOVE frmApp_Wind_CommSupplement.*  %dFolder%
MOVE frmApp_Wind_CommSupplement_0106.*  %dFolder%
MOVE frmApp_Wind_CommSupplement_New.*  %dFolder%
MOVE frmApp_Wind_Dwelling.*  %dFolder%
MOVE frmApp_Wind_Dwelling_0106.*  %dFolder%
MOVE frmApp_Wind_Dwelling_citw01rs0106_Page2.*  %dFolder%
MOVE frmApp_Wind_Dwelling_New.*  %dFolder%
MOVE frmApp_Wind_Dwelling_New_0703.*  %dFolder%
MOVE frmApp_Wind_Dwelling_New_0704.*  %dFolder%
MOVE frmApp_Wind_Dwelling_Page2.*  %dFolder%
MOVE frmApp_Wind_Dwelling_Page3.*  %dFolder%
MOVE frmApp_Wind_Losses.*  %dFolder%
MOVE frmApp_Wind_Losses_0106.*  %dFolder%
MOVE frmApp_Wind_Losses_0702.*  %dFolder%
MOVE frmApp_Wind_Losses_New.*  %dFolder%
MOVE frmApp_Wind_Losses_New2.*  %dFolder%
MOVE frmApp_Wind_Page2.*  %dFolder%
MOVE frmApp_Wind_Page2_New.*  %dFolder%
MOVE frmApp_Wind_Page2_New_0106.*  %dFolder%
MOVE frmApp_Wind_Page2_New_0703.*  %dFolder%
MOVE frmApp_Wind_Page2_Test.*  %dFolder%
MOVE frmApp_Wind_ResSupplement.*  %dFolder%
MOVE frmApp_Wind_ResSupplement_0106.*  %dFolder%
MOVE frmApp_Wind_ResSupplement_New.*  %dFolder%
MOVE frmApp_Wind_ResSupplement_New_0802.*  %dFolder%
MOVE frmApp_WindstormCertification.*  %dFolder%
MOVE frmcitw01crs71506.*  %dFolder%
MOVE frmCommercialPolicy.*  %dFolder%
MOVE frmCommercialResidential.*  %dFolder%
MOVE frmCommercialResidential_Modified.*  %dFolder%
MOVE frmComparison.*  %dFolder%
MOVE frmCostEstimator.*  %dFolder%
MOVE frmDPPrintout.*  %dFolder%
MOVE frmH04.*  %dFolder%
MOVE frmHO6.*  %dFolder%
MOVE frmHOPrintout.*  %dFolder%
MOVE frmLossMitigation_CPIC.*  %dFolder%
MOVE frmLossMitigation_CPIC_0204.*  %dFolder%
MOVE frmMVR.*  %dFolder%
MOVE frmRetrieveQuote.*  %dFolder%
MOVE frmSaveQuote.*  %dFolder%
MOVE frmScreenPrintout.*  %dFolder%
MOVE frmSpecialUnderwriting.*  %dFolder%
MOVE frmTerrLocatorb.*  %dFolder%
MOVE frmUtility.*  %dFolder%
MOVE frmWeb.*  %dFolder%
MOVE frmWindPrintout0704.*  %dFolder%
MOVE frmWorksheet_Args.*  %dFolder%
MOVE frmWorksheet_WindDwelling_040108.*  %dFolder%
MOVE frmWorksheet_WindPool_Dwelling_0707.*  %dFolder%
MOVE frmWorksheet_WindPool_Dwelling_MobileHome_0106.*  %dFolder%
MOVE frmWorksheet1_Page1.*  %dFolder%
MOVE frmWorksheet1_Page2.*  %dFolder%
MOVE frmWorksheet1_Page2_Modified.*  %dFolder%
MOVE frmWorksheet3_Page1.*  %dFolder%
MOVE frmWorksheet3_Page2.*  %dFolder%
MOVE frmWS_0106.*  %dFolder%
MOVE MainMenu.*  %dFolder%
MOVE Mobile_HO2_b.*  %dFolder%
MOVE Mobile_HO4.*  %dFolder%
MOVE SplashScreen.*  %dFolder%

@Pause
