@SET ssdir=\\AppSrvA\VSS$\QuickHomeforWindows\QHFL

SS DELETE $/7_6w/FORMS/frmAdditionalOptions.*
SS DELETE $/7_6w/FORMS/frmApp_FloodInsurance1.*
SS DELETE $/7_6w/FORMS/frmApp_FloodInsurance2.*
SS DELETE $/7_6w/FORMS/frmApp_FloodPreferred.*
SS DELETE $/7_6w/FORMS/frmApp_FloodPreferred2_050104a.*
SS DELETE $/7_6w/FORMS/frmApp_HomeOwners_100501.*
SS DELETE $/7_6w/FORMS/frmApp_ProducerCertification3.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_0108_Comm_citw01c_page1.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_0108_Comm_citw01c_page2.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_0108_Comm_citw01cr_Page3.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_0108_Comm_citw01cs_page1.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_0108_Comm_citw01cs_page2.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_0108_Commercial_citw01c_page1.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_0108_Commercial_citw01c_page2.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_0108_CommRes_citw01cnr_Page2.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_Comm.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_Comm_0106.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_Comm_071506.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_Comm_New.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_Comm_New_0703.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_Commercial_citw01cr1206page1.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_CommRes_citw01cr_Page1_0108.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_CommRes_citw01cr_Page1_1206.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_CommRes_citw01cr_Page2_0108.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_CommRes_citw01cr0108_Page3.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_CommRes_citw01cr1206page2.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_CommRes_citw01crc71506.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_CommRes_citw01crs_0108_Page2.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_CommRes_citw01crs_0108_Page3.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_CommRes_citw01crs_Page1_0108.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_CommRes_citw01crs_Page2_0108.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_CommRes_citw01crs_Page3_0108.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_CommRes_citw01crs1206Page1.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_CommRes_citw01crs1206Page2.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_CommSupplement.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_CommSupplement_0106.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_CommSupplement_New.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_Dwelling.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_Dwelling_0106.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_Dwelling_citw01rs0106_Page2.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_Dwelling_New.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_Dwelling_New_0703.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_Dwelling_New_0704.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_Dwelling_Page2.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_Dwelling_Page3.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_Losses.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_Losses_0106.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_Losses_0702.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_Losses_New.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_Losses_New2.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_Page2.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_Page2_New.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_Page2_New_0106.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_Page2_New_0703.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_Page2_Test.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_ResSupplement.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_ResSupplement_0106.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_ResSupplement_New.*
SS DELETE $/7_6w/FORMS/frmApp_Wind_ResSupplement_New_0802.*
SS DELETE $/7_6w/FORMS/frmApp_WindstormCertification.*
SS DELETE $/7_6w/FORMS/frmcitw01crs71506.*
SS DELETE $/7_6w/FORMS/frmCommercialPolicy.*
SS DELETE $/7_6w/FORMS/frmCommercialResidential.*
SS DELETE $/7_6w/FORMS/frmCommercialResidential_Modified.*
SS DELETE $/7_6w/FORMS/frmComparison.*
SS DELETE $/7_6w/FORMS/frmCostEstimator.*
SS DELETE $/7_6w/FORMS/frmDPPrintout.*
SS DELETE $/7_6w/FORMS/frmH04.*
SS DELETE $/7_6w/FORMS/frmHO6.*
SS DELETE $/7_6w/FORMS/frmHOPrintout.*
SS DELETE $/7_6w/FORMS/frmLossMitigation_CPIC.*
SS DELETE $/7_6w/FORMS/frmLossMitigation_CPIC_0204.*
SS DELETE $/7_6w/FORMS/frmMVR.*
SS DELETE $/7_6w/FORMS/frmRetrieveQuote.*
SS DELETE $/7_6w/FORMS/frmSaveQuote.*
SS DELETE $/7_6w/FORMS/frmScreenPrintout.*
SS DELETE $/7_6w/FORMS/frmSpecialUnderwriting.*
SS DELETE $/7_6w/FORMS/frmTerrLocatorb.*
SS DELETE $/7_6w/FORMS/frmUtility.*
SS DELETE $/7_6w/FORMS/frmWeb.*
SS DELETE $/7_6w/FORMS/frmWindPrintout0704.*
SS DELETE $/7_6w/FORMS/frmWorksheet_Args.*
SS DELETE $/7_6w/FORMS/frmWorksheet_WindDwelling_040108.*
SS DELETE $/7_6w/FORMS/frmWorksheet_WindPool_Dwelling_0707.*
SS DELETE $/7_6w/FORMS/frmWorksheet_WindPool_Dwelling_MobileHome_0106.*
SS DELETE $/7_6w/FORMS/frmWorksheet1_Page1.*
SS DELETE $/7_6w/FORMS/frmWorksheet1_Page2.*
SS DELETE $/7_6w/FORMS/frmWorksheet1_Page2_Modified.*
SS DELETE $/7_6w/FORMS/frmWorksheet3_Page1.*
SS DELETE $/7_6w/FORMS/frmWorksheet3_Page2.*
SS DELETE $/7_6w/FORMS/frmWS_0106.*
SS DELETE $/7_6w/FORMS/MainMenu.*
SS DELETE $/7_6w/FORMS/Mobile_HO2_b.*
SS DELETE $/7_6w/FORMS/Mobile_HO4.*
SS DELETE $/7_6w/FORMS/SplashScreen.*

@Pause
