AWSTemplateFormatVersion: "2010-09-09"

Resources:
  EC2IngressEgress:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: abc
      GroupDescription: The  Ingress/Egress security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 10.0.0.0/8
          Description: abc
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 10.0.0.0/8
          Description: abc
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 8083
          ToPort: 8083
          CidrIp: 10.0.0.0/8
          Description: def
