myFolder = "C:\CompareLog\BATCH02\DiffLogs"
' This Script generates a batch file doActions.bat that deletes files
' it reads from all the .TXT files in the given folder, those files contain
' the name of duplicate files in 2 servers.
'

If myFolder <> "" Then
    Set fso = CreateObject("Scripting.FileSystemObject")
    Set outFile = fso.CreateTextFile("C:\CompareLog\BATCH02\doActions.bat", True)
    outFile.WriteLine("REM  File AutoGenerated by " & WScript.ScriptName & " @:" & Now)
    outFile.WriteLine("")
    outFile.WriteLine("@SET logFile=C:\ActionLog.txt")
    outFile.WriteLine("@SET dACTION=MOVE")
    outFile.WriteLine("@SET dOPTIONS=/F /Q")
    outFile.WriteLine("")
    outFile.WriteLine("@COLOR 0C")
    outFile.WriteLine("@ECHO.")
    outFile.WriteLine("@ECHO   THIS BATCH FILE WILL DELETE FILES IN THE IMAGE SERVER")
    outFile.WriteLine("@ECHO       ONLY PROCEED IF YOU ARE ABSOLUTELY SURE!")
    outFile.WriteLine("@ECHO.")
    outFile.WriteLine("@PAUSE")
    outFile.WriteLine("@COLOR 0A")
    outFile.WriteLine("")
    Call ProcFolder(FSO.GetFolder(myFolder))
    outFile.WriteLine("")
    outFile.WriteLine("@ECHO.")
    outFile.WriteLine("@PAUSE")
    outFile.Close
    MsgBox "All Done!"
End If

'Loop through all the files in the folder
Sub ProcFolder(dFolder)
    For Each File In dFolder.Files
        If Ucase(Right(File.Name,4)) = ".TXT" then 
            Call ProcFile(File.Path)
        End If 
    Next
End Sub

'Start the reading of the txt file
Sub ProcFile(dFile)
    Set inFile     = fso.OpenTextFile(dFile, 1)
    Do until inFile.AtEndOfStream
        dLine = inFile.ReadLine
        If (Right(dLine, 9) = "identical") Then	
			dLine = Replace(dLine, "Files ","")
			dLine = Replace(dLine, " are identical","")
			arrFiles = Split(dLine," and ")
            strFile = Replace(arrFiles(1), "/","\")
            outFile.WriteLine("%dACTION% %dOPTIONS% """ & strFile & """ """ & strFile & ".ToDEL"" >> %logFile%")
        End If
    Loop
    inFile.Close    
End Sub
