myFolder = "E:\vbscript\RemoveDups"
' This Script generates a batch file doCompare.bat that compares folders
' it reads from all the .TXT files in the given folder, those files contain
' the name of the folders to compare.
'
' The batch file requires GNU DIFF: 
' http://gnuwin32.sourceforge.net/packages/diffutils.htm
'

If myFolder <> "" Then
    Set fso = CreateObject("Scripting.FileSystemObject")
	Set outFile = fso.CreateTextFile(myFolder & "\doCompare.bat", True)
	outFile.WriteLine("REM  File AutoGenerated by " & WScript.ScriptName & " @:" & Now)
	outFile.WriteLine("")    
	outFile.WriteLine("@SET logFile=C:\CompareLog\")
	outFile.WriteLine("@MD %logFile%")
	outFile.WriteLine("@SET cmd_DIFF=""C:\Program Files (x86)\GnuWin32\bin\diff.exe""")
	outFile.WriteLine("@SET cmd_OPTIONS=--binary --ignore-file-name-case --report-identical-files --recursive -q")
	outFile.WriteLine("")
	Call ProcFolder(FSO.GetFolder(myFolder))
	outFile.WriteLine("@ECHO.")
	outFile.WriteLine("@PAUSE")
	outFile.Close
    MsgBox "All Done!"
End If


'Loop through all the files in the folder
Sub ProcFolder(dFolder)
	For Each File In dFolder.Files
		If Ucase(Right(File.Name,4)) = ".TXT" then 
			Call ProcFile(File.Path)
		End If 
	Next
End Sub

'Start the reading of the txt file
Sub ProcFile(dFile)
    '   Wscript.Echo dFile
    Set inFile 	= fso.OpenTextFile(dFile, 1)
    'First line contains compare info
    dCompare = Trim(Replace(inFile.ReadLine, "Compare", ""))
    dFolders = Split(dCompare, " with ")
    
    Do until inFile.AtEndOfStream
        dLine = inFile.ReadLine
        'Make sure the folder is a valid QQID
        If Left(dLine,2) = "QQ" And Mid(dLine, 9, 1) = "," Then
            dQQID = Mid(dLine, 1, 8)            
            Call CompareFolders(fso.BuildPath(dFolders(0), dQQID), fso.BuildPath(dFolders(1), dQQID), dQQID)
        End If
    Loop
    inFile.Close    
End Sub

Sub CompareFolders(strFolder1, strFolder2, strQQID)
    outFile.WriteLine("%cmd_DIFF% %cmd_OPTIONS% " & strFolder1 & " " & strFolder2 & " >> %logFile%" & strQQID & ".txt" )
End Sub
